version: '3.3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/bookworm.musaffarulislam.com
      - ./nginx-conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/bookworm.musaffarulislam.com
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/bookworm.musaffarulislam.com --email ubuntu@ip-172-31-34-6 --agree-tos --no-eff-email --staging -d bookworm.musaffarulislam.com -d www.bookworm.musaffarulislam.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Bookworm-EcommerceApp-Node-MongoDB-Ejs/views/
      o: bind

networks:
  app-network:
    driver: bridge



  # mongo:
  #   image: mongo
  #   restart: unless-stopped
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - /home/ubuntu/mongodata:/data/db
  #   networks:
  #     - app-network