version: "3.8"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/mongodata:/data/db
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # Add port mapping for SSL
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      # - /path/to/your/nodejs/app:/var/www/bookworm.musaffarulislam.com # <-- Update this line with the correct path to your Node.js app
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  app-network:
  web-root:
    driver: local

networks:
  app-network:
    driver: bridge
