version: "3.8"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/mongodata:/data/db
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # Add port mapping for SSL
    volumes:
      - web-root:/var/www/bookworm.musaffarulislam.com
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/certbot-etc:/etc/letsencrypt
      - ./nginx-conf/certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx-conf/certbot-etc:/etc/letsencrypt
      - ./nginx-conf/certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/bookworm.musaffarulislam.com
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/bookworm.musaffarulislam.com/Bookworm-EcommerceApp-Node-MongoDB-Ejs --email dev.musaffarulislam@gmail.com --agree-tos --no-eff-email --staging -d bookworm.musaffarulislam.com -d www.bookworm.musaffarulislam.com

volumes:
  certbot-etc:
    driver: local
  certbot-var:
    driver: local
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Bookworm-EcommerceApp-Node-MongoDB-Ejs/nginx-conf/web-root

networks:
  app-network:
    driver: bridge
