version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/mongodata:/data/db
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo

  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    volumes:
      - /path/to/your/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - nodejs

  letsencrypt:
    container_name: 'certbot-service'
    image: certbot/certbot
    command: sh -c "certbot certonly --webroot -w /tmp/acme_challenge -d bookworm.musaffarulislam.com --text --agree-tos --email dev.musaffarulislam@gmail.com --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/tmp/acme_challenge:/tmp/acme_challenge"
    environment:
      - TERM=xterm

networks:
  app-network:
    driver: bridge
