version: "3.8"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/mongodata:/data/db
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo

  # webserver:
  #   image: nginx:mainline-alpine
  #   container_name: webserver
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443" # Add port mapping for SSL
  #   volumes:
  #     - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
  #     - /app:/var/www/bookworm.musaffarulislam.com # <-- Update this line with the correct path to your Node.js app
  #   depends_on:
  #     - nodejs
  #   networks:
  #     - app-network

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/bookworm.musaffarulislam.com/Bookworm-EcommerceApp-Node-MongoDB-Ejs
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/bookworm.musaffarulislam.com/Bookworm-EcommerceApp-Node-MongoDB-Ejs
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/bookworm.musaffarulislam.com/Bookworm-EcommerceApp-Node-MongoDB-Ejs --email dev.musaffarulislam@gmail.com --agree-tos --no-eff-email --staging -d bookworm.musaffarulislam.com -d www.bookworm.musaffarulislam.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/sammy/node_project/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
