services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/mongodata:/data/db
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo

nginx:
    image: nginx:1.23.3-alpine
    restart: always
    volumes:
      - /path/to/your/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - nodejs

networks:
  app-network:
    driver: bridge